server:
  port: 8081

jasypt:
  encryptor:
    bean: jasyptEncryptor


spring:
  mustache:
    expose-session-attributes: true
  profiles:
    active: dev
  security:
    oauth2:
      client:
        registration:
          google: # /oauth2/authorization/google 이 주소를 동작하게 한다.
            client-id: ENC(3P13X0MEc7WH3Hchx8s4PEGFNbGL7s0QOeISXx+sxYlX1TByJ/HnXJHERDPmywLCbhlFoxp1yczmkj3g7IWUReIB2vHRkaLF/9AuaA5jnWwEexSVlyTRNw==)
            client-secret: ENC(SccKsp2Z/9tA3396ftHJRpjlPwTE7Hz7ushjsfTySrQ31L65u0X8dg==)
            scope:
            - email
            - profile


---
spring:
  profiles: local
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
    schema: classpath*:sql/schema.sql
    data: classpath*:sql/data.sql
  jpa:
    show-sql: true
    propertice:
  hibernate:
    fomat_sql: true
    ddl-auto: update
  h2:
   console:
    enabled: true
---

 spring:
   profiles: dev
   datasource:
     sql-script-encoding: UTF-8
     url: jdbc:mariadb://localhost:3306/proptech
     username: ENC(LyzpWYaIfBHycYC0uOJw6w==)
     password: ENC(/j9TCvgQDkpQWHi2dq56ag==)
     driver-class-name: org.mariadb.jdbc.Driver
---
