
 server:
   port: 8081

 spring:
   profiles:
     active: local
     #active: local # 로컬환경
---
 spring:
   datasource:
    schema: classpath*:sql/schema.sql
    data: classpath*:sql/data.sql

   profiles: local
   jpa:
     show-sql: true
     propertice:
       hibernate:
         fomat_sql: true
         ddl-auto: create-drop
   h2:
     console:
       enabled: true
---

 spring:
   profiles: dev
   datasource:
    url: jdbc:mariadb://localhost:3306/proptech
    username : GUNS
    password: GUNS
    driver-class-name: org.mariadb.jdbc.Driver
---
