
 server:
   port: 8081



 spring:
   profiles:
     active: local
     #active: local # 로컬환경
---

 spring:
   profiles: local
   jpa:
     show-sql: true
     propertice:
       hibernate:
         fomat_sql: true
         # ddl-auto: create-drop
   h2:
     console:
       enabled: true
---

 spring:
   profiles: dev
   datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username : myAdmin
    password: admin
    driver-class-name: org.mariadb.jdbc.Driver
---
